#!/usr/bin/env python3
import os, sys
import errno
import yaml
import argparse
import etcd3
import json
import time
from collections import Mapping, Sequence
from maestro_util import *

class Cluster(object):
    def emit_value(self, path, value):
        try:
            res = client.put(path, str(value))
        except Exception as e:
            print("Error {0} setting {1} : {2}".format(str(e), path, str(value)))

    def check_key(self, key):
        # Handle forward slash in keys e.g. endpoints containing "/" in the name
        try:
            if '/' in key:
                print(f'Error: "/" is not a supported character in key name {key}')
                sys.exit(1)
            return key
        except Exception as e:
            print(str(e))

    def walk(self, obj, path=''):
        if obj is None:
            if path.split("/")[-1] in CORE_ATTRS:
                print(f'{path.split("/")[-1]} not present in ldms yaml configuration file.\nContinuing..')
        elif isinstance(obj, Mapping):
            for key in obj:
                safe_key = self.check_key(key)
                self.walk(obj[key], '{0}/{1}'.format(path, safe_key))
        elif isinstance(obj, Sequence):
            if isinstance(obj, (str, bytearray)):
                self.emit_value(path, obj)
            else:
                item = 0
                for v in obj:
                    # we want keys to be returned in numerical order which requires z-fill
                    self.walk(v, path + '/{0:06}'.format(item))
                    item += 1
        elif obj:
            self.emit_value(path, obj)

    def build_daemons(self, config):
        """Generate a daemon spec list from YAML config

        Builds a dictionary of endpoint definitions. The 'config' is a
        list of daemon specifications. Each daemon specification contains
        'names', 'host', and 'endpoint' attributes. All attributes are
        expanded per the slurm hostlist rules. The length of the
        expanded name-list, must equal the length of the expanded
        host-list.

        Example:

        daemons:
          - names : "agg-[1-10]"
            hosts : "node[1-10]"
            endpoints :
              - names : "node-[1-10]-[10002]
                ports : "[10002]"
                maestro_comm : True
                xprt : sock
                auth :
                  name : munge

        results in the following host-spec dictionary:

        {
        "agg-[[1-3]-[10002]" : {
          "agg-1" : {
            "endpoints": {
              "node-1-10002" : { "host" : "node-1", "port" : 10002 },
              "node-2-10002" : { "host" : "node-2", "port" : 10002 },
              "node-3-10002" : { "host" : "node-3", "port" : 10002 },
              ...
            }
          }
        }

        """
        ep_dict = {}
        node_config = config['daemons']
        for spec in node_config:
            check_required([ 'names', 'endpoints', 'hosts' ],
                           spec, "daemons specification")
            hosts = expand_names(spec['hosts'])
            dnames = expand_names(spec['names'])
            ep_names = []
            ports = []
            for endpoints in spec['endpoints']:
                check_required(['names','ports'],
                               endpoints, 'endpoint specification')
                ep_names.append(expand_names(endpoints['names']))
                epnames = expand_names(endpoints['names'])
                ep_ports = expand_names(endpoints['ports'])
                if len(ep_ports) != len(epnames):
                    ep_ports += [ ep_ports[0] for i in range(0, len(epnames)) ]
                ports.append(ep_ports)
            ep_dict[spec['names']] = {}
            for dname, host in zip(dnames, hosts):
                ep_dict[spec['names']][dname] = {}
                ep_dict[spec['names']][dname]['endpoints'] = {}
                for ep_, ep_port, ep in zip(ep_names, ports, spec['endpoints']):
                    port = ep_port.pop(0)
                    ep_name = ep_.pop(0)
                    xprt = check_opt('xprt', ep)
                    auth_name = check_opt('auth', ep)
                    auth_conf = check_opt('conf', ep)
                    maestro_comm = parse_yaml_bool(check_opt('maestro_comm', ep))
                    h = {
                        'name' : ep_name,
                        'addr' : host,
                        'port' : port,
                        'xprt' : xprt,
                        'maestro_comm' : maestro_comm,
                        'auth' : { 'name' : auth_name, 'conf' : auth_conf }
                    }
                    ep_dict[spec['names']][dname]['endpoints'][ep_name] = h
        return ep_dict

    def build_groups(self, config):
        groups = {}
        if 'daemons' not in config:
            return groups
        group_conf = config['daemons']
        for group_spec in group_conf:
            check_required([ 'names', 'hosts', 'endpoints'],
                           group_spec, "daemon specification")
            endpoints = []
            for ep in group_spec['endpoints']:
                endpoints += expand_names(ep['names'])
            group_name = group_spec['names']
            hosts = expand_names(group_spec['hosts'])
            group = {
                'name'       : group_name,
                'hosts'      : hosts,
                'endpoints'  : endpoints,
            }
            groups[group_name] = group
        return groups

    def build_aggregators(self, config):
        aggregators = {}
        if 'aggregators' not in config:
            return aggregators
        agg_conf = config['aggregators']
        for agg_spec in agg_conf:
            check_required([ 'daemons' ],
                           agg_spec, "aggregator specification")
            names = expand_names(agg_spec['daemons'])
            group = agg_spec['daemons']
            endpoints = []
            daemons_ = None
            for daemons in config['daemons']:
                if group == daemons['names']:
                    daemons_ = daemons
            if daemons_ is None:
                raise ValueError(f"No daemons matched matched daemon key {group}")
            for eps in daemons_['endpoints']:
                if eps['maestro_comm'] is True:
                    endpoints += expand_names(eps['names'])
            if group not in aggregators:
                aggregators[group] = []
            for name in names:
                endpoint = endpoints.pop(0)
                agg = {
                        'name'      : name,
                        'state'     : 'stopped' # 'running', 'error'
                }
                aggregators[group].append(agg)
        return aggregators

    def build_producers(self, config):
        """
        Return a dictionary keyed by the group name. Each dictionary
        entry is a list of producers in that group.
        """
        producers = {}
        for agg in config['aggregators']:
            if 'peers' not in agg:
                continue
            for prod in agg['peers']:
                check_required([ 'endpoints', 'updaters',
                                 'reconnect', 'type', ],
                               prod, '"producer" entry')
                # Use endpoints for producer names and remove names attribute?
                daemons = prod['daemons']
                names = expand_names(prod['endpoints'])
                endpoints = expand_names(prod['endpoints'])
                group = agg['daemons']
                smplr_dmns = expand_names(prod['daemons'])
                if group not in producers:
                    producers[group] = {}

                subscribe = check_opt('subscribe', prod)
                if len(names) != len(endpoints):
                    raise ValueError('"producer": The "host" and "name" specifications must '
                                     '            expand to the same number of strings')
                upd_spec = prod['updaters']
                # Expand and generate all the producers
                typ = prod['type']
                reconnect = cvt_intrvl_str_to_us(prod['reconnect'])
                for name in names:
                    smplr_dmn = smplr_dmns.pop(0)
                    endpoint = endpoints.pop(0)
                    prod = {
                        'daemon'    : smplr_dmn,
                        'dmn_grp'   : daemons,
                        'name'      : name,
                        'endpoint'  : endpoint,
                        'type'      : typ,
                        'group'     : group,
                        'reconnect' : reconnect,
                        'updaters'  : upd_spec
                    }
                    if subscribe:
                        prod['subscribe'] = subscribe
                    producers[group][endpoint] = prod
        return producers

    def build_updaters(self, config):
        """
        Return a dictionary based on the aggregator. Each dictionary
        entry is a list of updaters in that group.
        """
        updaters = {}
        updtr_cnt = 0
        for agg in config['aggregators']:
            if 'peers' not in agg:
                continue
            for prod in agg['peers']:
                for updtr_spec in prod['updaters']:
                    check_required([ 'interval', 'sets', ],
                                   updtr_spec, '"updater" entry')
                    group = agg['daemons']
                    if group not in updaters:
                        updaters[group] = {}
                    grp_updaters = updaters[group]
                    updtr_name = f'updtr_{updtr_cnt}'
                    if updtr_name in grp_updaters:
                        raise ValueError(f"Duplicate updater name '{updtr_name}''. "\
                                         f"An updater name must be unique within the group")
                    updtr = {
                        'name'      : updtr_name,
                        'interval'  : cvt_intrvl_str_to_us(updtr_spec['interval']),
                        'group'     : agg['daemons'],
                        'sets'      : updtr_spec['sets'],
                        'producers' : [{ 'regex' : '.*' }]
                    }
                    if 'offset' in updtr_spec:
                        updtr['offset'] = cvt_intrvl_str_to_us(updtr_spec['offset'])
                    if 'auto' in updtr_spec and 'push' in updtr_spec:
                        raise ValueError(f"The updater specification: {json.dumps(updtr_spec)} "
                                          "contains both 'push' and 'auto' which are "
                                          "mutually exclusive")
                    if 'auto' in updtr_spec:
                        updtr['auto'] = updtr_spec['auto']
                    if 'push' in updtr_spec:
                        updtr['push'] = updtr_spec['push']
                    grp_updaters[updtr_name] = updtr
                    updtr_cnt += 1
        return updaters

    def build_stores(self, config):
        """
        Return a dictionary keyed by the group name. Each dictionary
        entry is a list of stores in that group.
        """
        if 'stores' not in config:
            return None
        stores = {}
        for store_spec in config['stores']:
            check_required([ 'name', 'plugin', 'container', 'schema' ],
                           store_spec, '"store" entry')
            group = store_spec['daemons']
            if group not in stores:
                stores[group] = {}
            grp_stores = stores[group]
            store_name = store_spec['name']
            if store_name in grp_stores:
                raise ValueError(f"Duplicate store name '{store_name}''. "
                            "A store name must be unique within the group")

            check_required([ 'name', 'config'],
                           store_spec['plugin'],
                           '"store plugin" entry')
            grp_stores[store_name] = store_spec
        return stores

    def build_samplers(self, config):
        """
        Generate samplers from YAML config.
        Return a dictionary keyed by the samplers group name. Each dictionary
        entry is a single ldms daemon's sampler configuration.
        """
        if 'samplers' not in config:
            return None
        smplrs = {}
        for smplr_spec in config['samplers']:
            check_required([ 'daemons', 'plugins' ],
                           smplr_spec, '"sampler" entry')
            for plugin in smplr_spec['plugins']:
                check_required(['name'], plugin, 'plugin entry')
            smplrs[smplr_spec['daemons']] = smplr_spec
        return smplrs

    def build_plugins(self, config):
        """
        Generate plugins to load from a YAML config.
        Return a dictionary keyed by the plugin's group name. Each dictionary entry
        is a single plugin's configuration.
        """
        if 'plugins' not in config:
            return None
        plugins = {}
        for plugn_spec in config['plugins']:
            check_required([ 'name', 'config' ],
                           plugn_spec, '"plugin" entry')
            group = plugn_spec['daemons']
            if group not in plugins:
                plugins[group] = {}
            grp_plugins = plugins[group]
            plugin_name = plugn_spec['name']
            if plugin_name in grp_plugins:
                raise ValueError(f'Duplicate plugin name "{plugin_name}". '
                                  'Plugin must be unique within a group.')
            grp_plugins[plugin_name] = plugn_spec
        return plugins

    def __init__(self, client, name, cluster_config):
        """
        """
        self.client = client
        self.name = name
        self.cluster_config = cluster_config
        self.daemons = self.build_daemons(cluster_config)
        self.aggregators = self.build_aggregators(cluster_config)
        self.groups = self.build_groups(cluster_config)
        self.producers = self.build_producers(cluster_config)
        self.updaters = self.build_updaters(cluster_config)
        self.stores = self.build_stores(cluster_config)
        self.samplers = self.build_samplers(cluster_config)
        self.plugins = self.build_plugins(cluster_config)

    def commit(self):
        pass

    def save_config(self):
        try:
            self.client.delete_prefix('/' + self.name)
            self.walk(self.daemons, '/' + self.name + '/daemons')
            self.walk(self.aggregators, '/' + self.name + '/aggregators')
            self.walk(self.groups, '/' + self.name + '/groups')
            self.walk(self.producers, '/' + self.name + '/producers')
            self.walk(self.updaters, '/' + self.name + '/updaters')
            self.walk(self.stores, '/' + self.name + '/stores')
            self.walk(self.samplers, '/' + self.name + '/samplers')
            self.walk(self.plugins, '/' + self.name + '/plugins')
            self.client.put('/'+self.name+'/last_updated', str(time.time()))
        except Exception as e:
            a, b, c = sys.exc_info()
            print(str(e)+' '+str(c.tb_lineno))
            return 1

    def write_opt_attr(self, fd, attr, val, endline=True):
        # Include leading space
        if attr is not None:
            fd.write(f' {attr}={val}')
        if endline:
            fd.write(f'\n')

    def write_producers(self, fd, group_name):
        #Writes producer configuration to file fd
        if group_name in self.producers:
            ''' Balance samplers across aggregators '''
            prdcrs = []
            loop = round(len(self.producers[group_name]) / len(self.aggregators[group_name]))
            last_sampler = None
            for prdcr in self.producers[group_name]:
                prdcrs.append(prdcr)
            if not last_sampler:
                idx = 0
            else:
                idx = prdcrs.index(last_sampler) + 1
            prod_group = list(self.producers[group_name].keys())[idx:]
            i = 0
            auth = None
            auths = {}
            for ep in self.producers[group_name]:
                producer = self.producers[group_name][ep]
                auth = check_opt('auth', self.daemons[producer['dmn_grp']][producer['daemon']]['endpoints'][ep])
                auth_opt = check_opt('conf', self.daemons[producer['dmn_grp']][producer['daemon']]['endpoints'][ep])
                if auth in auths:
                    continue
                else:
                    auths[auth] = { 'conf' : auth_opt }
            for auth in auths:
                fd.write(f'auth_add name={auth}')
                self.write_opt_attr(fd, 'conf', auths[auth]['conf'])
            for ep in prod_group:
                if i >= loop:
                    break
                regex = False
                producer = self.producers[group_name][ep]
                pname = producer['name']
                port = self.daemons[producer['dmn_grp']][producer['daemon']]['endpoints'][ep]['port']
                xprt = self.daemons[producer['dmn_grp']][producer['daemon']]['endpoints'][ep]['xprt']
                hostname = self.daemons[producer['dmn_grp']][producer['daemon']]['endpoints'][ep]['addr']
                ptype = producer['type']
                interval = producer['reconnect']
                fd.write(f'prdcr_add name={pname} '+
                         f'host={hostname} '+
                         f'port={port} '+
                         f'xprt={xprt} type={ptype} interval={interval}\n')
                last_sampler = pname
                i += 1
                if 'regex' in producer:
                    regex = True
                    fd.write(f'prdcr_start_regex regex={producer["regex"]}\n')
                if not regex:
                    fd.write(f'prdcr_start_regex regex=.*\n')

    def write_samplers(self, fd, smplr_group):
        for sampler in self.samplers[smplr_group]['plugins']:
            cfg_str = parse_to_cfg_str(sampler['config'])
            sname = sampler['name']
            interval = cvt_intrvl_str_to_us(sampler['interval'])
            fd.write(f'load name={sname}\n')
            fd.write(f'config {cfg_str} producer=${{HOSTNAME}} '+
                     f'component_id=${{COMPONENT_ID}} '+
                     f'instance=${{HOSTNAME}}/{sname}\n')
            fd.write(f'start name={sname} interval={interval}')
            offset = check_opt('offset', sampler)
            self.write_opt_attr(fd, 'offset', offset)

    def write_sampler_plugins(self, group_name):
        if self.plugins != None:
            if group_name in self.plugins:
                fd = open(f'{path}/{group_name}-samplers.conf', 'w+')
                for plugin in self.plugins[group_name]:
                    cfg_str = parse_to_cfg_str(self.plugins[group_name][plugin]['config'])
                    fd.write(f'load name={plugin}\n')
                    fd.write(f'config name={plugin} {cfg_str}\n\n')
                fd.close()

    def write_agg_plugins(self, fd, group_name):
        # Write independent plugin configuration for group <group_name>
        if self.plugins != None:
            if group_name in self.plugins:
                for plugin in self.plugins[group_name]:
                    cfg_str = parse_to_cfg_str(self.plugins[group_name][plugin]['config'])
                    if 'stream' in self.plugins[group_name][plugin]['config']:
                        if 'regex' in self.plugins[group_name][plugin]['config']:
                            regex = self.plugins[group_name][plugin]['config']
                            fd.write(f'prdcr_subscribe stream={self.plugins[group_name][plugin]["config"]["stream"]} '\
                                     f'regex={regex}\n')
                        else:
                            fd.write(f'prdcr_subscribe stream={self.plugins[group_name][plugin]["config"]["stream"]} '\
                                     f'regex=.*\n')
                    fd.write(f'load name={plugin}\n')
                    fd.write(f'config name={plugin} {cfg_str}\n\n')

    def write_updaters(self, fd, group_name):
        if group_name in self.updaters:
            updtr_group = self.updaters[group_name]
            for updtr in updtr_group:
                interval = cvt_intrvl_str_to_us(updtr_group[updtr]['interval'])
                updtr_str = f'updtr_add name={updtr_group[updtr]["name"]} '
                if 'mode' in updtr_group[updtr]:
                    mode = updtr_group[updtr]['mode']
                else:
                    mode = 'static'
                # Check mode
                if mode == 'push':
                    updtr_str += 'push=onchange\n'
                elif mode == 'auto_interval':
                    updtr_str += 'auto_interval=True\n'
                fd.write(f'updtr_add name={updtr_group[updtr]["name"]} '+
                         f'interval={interval}')
                offset = check_opt('offset', updtr_group[updtr])
                self.write_opt_attr(fd, 'offset', offset)
                for prod in updtr_group[updtr]['producers']:
                    fd.write(f'updtr_prdcr_add name={updtr_group[updtr]["name"]} '+
                             f'regex={prod["regex"]}\n')
                fd.write(f'updtr_start name={updtr_group[updtr]["name"]}\n')

    def write_stores(self, fd, group_name):
        if group_name in self.stores:
            store_group = self.stores[group_name]
            loaded_plugins = []
            for store in store_group:
                if store_group[store]["plugin"]["name"] not in loaded_plugins:
                    fd.write(f'load name={store_group[store]["plugin"]["name"]}\n')
                    fd.write(f'config name={store_group[store]["plugin"]["name"]} '+
                             f'{parse_to_cfg_str(store_group[store]["plugin"]["config"])}\n')
                    loaded_plugins.append(store_group[store]["plugin"]["name"])
                strgp_add = f'strgp_add name={store} plugin={store_group[store]["plugin"]["name"]} '
                strgp_add += f'container={store_group[store]["container"]} '
                strgp_add += f'schema={store_group[store]["schema"]}'
                fd.write(strgp_add)
                flush = check_opt('flush', store_group[store])
                self.write_opt_attr(fd, 'flush', flush)
                fd.write(f'strgp_start name={store}\n')

    def config_v4(self, path):
        """
        Read the group configuration from ETCD and generate a version 4 LDMSD configuration
        This configuration assumes that the environemnt variables COMPONENT_ID, HOSTNAME
        all exist on the machines relevant to the ldmsd cluster.
        """
        for group_name in self.groups:
            # Load sampler statements
            group = self.groups[group_name]

            # Sampler config
            if self.samplers != None:
                try:
                    self.write_sampler_plugins(self)
                    for smplr_group in self.samplers:
                        # TO DO: Refactor sampler config architecture to more easily reference appropriate groups
                        if group_name != smplr_group:
                            continue
                        fd = open(f'{path}/{group_name}-samplers.conf', 'w+')
                        self.write_samplers(fd, smplr_group)
                    if fd:
                        fd.close()
                except Exception as e:
                    a, b, d = sys.exc_info()
                    print(f'Error generating sampler configuration: {str(e)} {str(d.tb_lineno)}')
                    raise ValueError
            else:
                print(f'"samplers" not found in configuration file. Skipping...')

            # Agg config
            try:
                ''' "Balance" agg configuration if all samplers are included in each aggregator '''
                if group_name not in self.aggregators:
                    continue
                last_sampler = None
                for agg in self.aggregators[group_name]:
                    fd = open(f'{path}/{group_name}-{agg["name"]}.conf', 'w+')
                    self.write_producers(fd, group_name)
                    self.write_agg_plugins(fd, group_name)
                    self.write_updaters(fd, group_name)
                    self.write_stores(fd, group_name)
            except Exception as e:
                ea, eb, ec = sys.exc_info()
                print('Agg config Error: '+str(e)+' Line:'+str(ec.tb_lineno))
                raise ValueError

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="LDMS Monitoring Cluster Configuration")
    parser.add_argument("--cluster", metavar="FILE", required=True,
                        help="The name of the etcd cluster configuration file")
    parser.add_argument("--ldms_config", metavar="FILE", required=True,
                        help="The ldmsd load balance domain configuration file. "
                        "This will not start the maestro "
                        "load balancer")
    parser.add_argument("--prefix", metavar="STRING", required=True,
                        help="The prefix for the dumped aggregator configurations",
                        default="unknown")
    parser.add_argument("--generate-config-path", metavar="STRING", required=False,
                        default=False)
    parser.add_argument("--version", metavar="VERSION",
                        help="The OVIS version for the output syntax (4 or 5), default is 4",
                        default=4)
    args = parser.parse_args()

    # Load the cluster configuration file. This configures the daemons
    # that support the key/value configuration database
    etcd_fp = open(args.cluster)
    etcd_spec = yaml.safe_load(etcd_fp)

    pfx = etcd_spec['cluster']
    etcd_hosts = ()
    for h in etcd_spec['members']:
        etcd_hosts += (( h['host'], h['port'] ),)

    # All keys in the DB are prefixed with the cluster name, 'pfx'. So we can
    # have multiple monitoring hosted by the same consensus cluster.
    config_fp = open(args.ldms_config)
    conf_spec = yaml.safe_load(config_fp)

    # Use the 1st host for now
    client = etcd3.client(host=etcd_hosts[0][0], port=etcd_hosts[0][1],
        grpc_options=[ ('grpc.max_send_message_length',16*1024*1024),
                       ('grpc.max_receive_message_length',16*1024*1024)])

    cluster = Cluster(client, args.prefix, conf_spec)
    if args.generate_config_path:
        cluster.config_v4(args.generate_config_path)
        print("LDMSD v4 config files generated")
        sys.exit(0)

    # blow away the existing configuration
    rc = cluster.save_config()
    if rc:
        print("Error saving ldms cluster configuration to etcd cluster")
        sys.exit(0)
    print("LDMS aggregator configuration saved to etcd cluster.")

    sys.exit(0)
