#!/usr/bin/env python3
import os, sys
import errno
import yaml
import argparse
import etcd3
import json
import time
from collections import Mapping, Sequence
from maestro_util import cvt_intrvl_str_to_us, expand_names

class Cluster(object):
    def emit_value(self, path, value):
        try:
            res = client.put(path, str(value))
        except Exception as e:
            print("Error {0} setting {1} : {2}".format(str(e), path, str(value)))

    def walk(self, obj, path=''):
        if isinstance(obj, Mapping):
            for key in obj:
                self.walk(obj[key], '{0}/{1}'.format(path, str(key)))
        elif isinstance(obj, Sequence):
            if isinstance(obj, (str, bytearray)):
                self.emit_value(path, obj)
            else:
                item = 0
                for v in obj:
                    # we want keys to be returned in numerical order which requires z-fill
                    self.walk(v, path + '/{0:06}'.format(item))
                    item += 1
        elif obj:
            self.emit_value(path, obj)

    def check_required(self, attr_list, container, container_name):
        """Verify that each name in attr_list is in the container"""
        for name in attr_list:
            if name not in container:
                raise ValueError("The '{0}' attribute is required in a {1}".
                                 format(name, container_name))

    def build_endpoints(self, config):
        """Generate an endpoint spec list from YAML config

        Builds a dictionary of endpoint definitions. The 'config' is a
        list of endpoint specifications. Each endpoint specification contains
        'name', 'host', and 'port' attributes. All attributes are
        expanded per the slurm hostlist rules. The length of the
        expanded name-list, must equal the length of the expanded
        host-list times the expanded port-list.

        Example:

        names : "nid[0001-0002]-[10001-10002]"
        hosts : "nid[0001-0002]"
        ports : "[10001-10002]"

        results in the following host-spec dictionary:

        {
        "nid0001-10001" : { "host" : "nid0001", "port" : 10001 },
        "nid0001-10002" : { "host" : "nid0001", "port" : 10002 },
        "nid0002-10001" : { "host" : "nid0002", "port" : 10001 },
        "nid0002-10002" : { "host" : "nid0002", "port" : 10002 }
        }

        """
        ep_dict = {}
        if 'endpoints' not in config:
            return ep_dict

        node_config = config['endpoints']
        for spec in node_config:
            self.check_required([ 'names', 'hosts', 'ports' ],
                                spec, "host specification")
            names = expand_names(spec['names'])
            hosts = expand_names(spec['hosts'])
            ports = expand_names(spec['ports'])
            if 'xprt' in spec:
                xprt = spec['xprt']
            else:
                xprt = 'sock'
            if 'auth' in spec:
                auth = spec['auth']
                self.check_required([ 'name' ],
                                    auth, "authentication configuration")
                auth_name = auth['name']
                if 'conf' in auth:
                    auth_config = auth['conf']
                else:
                    auth_config = ""
            else:
                auth_name = 'none'
                auth_config = ""
            group = spec['group']
            # build compute for each host x port
            for host in hosts:
                for port in ports:
                    name = names.pop(0)
                    h = {
                        'name'  : name,
                        'group' : group,
                        'addr'  : host,
                        'port'  : port,
                        'xprt'  : xprt,
                        'auth'  : { 'name' : auth_name, 'conf' : auth_config }
                    }
                    ep_dict[name] = h

        return ep_dict

    def build_groups(self, config):
        groups = {}
        if 'groups' not in config:
            return groups
        group_conf = config['groups']
        for group_spec in group_conf:
            self.check_required(['name', 'endpoints'],
                                group_spec, "daemon specification")
            endpoints = expand_names(group_spec['endpoints'])
            group_name = group_spec['name']
            if 'interfaces' in group_spec:
                interfaces = expand_names(group_spec['interfaces'])
            else:
                interfaces= []
            group = {
                'name'       : group_name,
                'endpoints'  : endpoints,
                'interfaces' : interfaces
            }
            groups[group_name] = group
        return groups

    def build_aggregators(self, config):
        aggregators = {}
        if 'aggregators' not in config:
            return aggregators

        agg_conf = config['aggregators']
        for agg_spec in agg_conf:
            self.check_required([ 'names', 'group', 'endpoints' ],
                                agg_spec, "aggregator specification")

            names = expand_names(agg_spec['names'])
            group = agg_spec['group']
            if group not in aggregators:
                aggregators[group] = []
            endpoints = expand_names(agg_spec['endpoints'])
            if len(names) != len(endpoints):
                raise ValueError('"aggregators:" The "host" and "name" specifications must '
                                'expand to the same number of names')
            for name in names:
                endpoint = endpoints.pop(0)
                agg = {
                        'name'      : name,
                        'endpoint'  : endpoint,
                        'state'     : 'stopped' # 'running', 'error'
                }
                aggregators[group].append(agg)
        return aggregators

    def build_producers(self, config):
        """
        Return a dictionary keyed by the group name. Each dictionary
        entry is a list of producers in that group.
        """
        producers = {}
        if 'producers' not in config:
            return producers
        prod_spec = config['producers']
        for prod in prod_spec:
            self.check_required([ 'names', 'endpoints', 'updaters',
                                  'reconnect', 'type', 'group' ],
                                prod, '"producer" entry')
            names = expand_names(prod['names'])
            endpoints = expand_names(prod['endpoints'])
            group = prod['group']
            if group not in producers:
                producers[group] = []

            if 'subscribe' in prod:
                subscribe = prod['subscribe']
            else:
                subscribe = None
            if 'auth' in prod:
                auth = prod['auth']
            else:
                auth = None
            if len(names) != len(endpoints):
                raise ValueError('"producer": The "host" and "name" specifications must '
                                'expand to the same number of strings')
            upd_spec = prod['updaters']

            # Expand and generate all the producers
            typ = prod['type']
            reconnect = cvt_intrvl_str_to_us(prod['reconnect'])
            for name in names:
                endpoint = endpoints.pop(0)
                smplr_group = self.endpoints[endpoint]['group']
                prod = {
                    'name'      : name,
                    'endpoint'  : endpoint,
                    'type'      : typ,
                    'group'     : smplr_group,
                    'reconnect' : reconnect,
                    'updaters'  : upd_spec,
                    'auth'      : auth
                }
                if subscribe:
                    prod['subscribe'] = subscribe
                producers[group].append(prod)
        return producers

    def build_updaters(self, config):
        """
        Return a dictionary keyed by the group name. Each dictionary
        entry is a list of updaters in that group.
        """
        updaters = {}
        if 'updaters' not in config:
            return updaters
        for updtr_spec in config['updaters']:
            self.check_required([ 'name', 'group', 'interval', 'sets', 'producers' ],
                                updtr_spec, '"updater" entry')
            group = updtr_spec['group']
            if group not in updaters:
                updaters[group] = {}
            grp_updaters = updaters[group]
            updtr_name = updtr_spec['name']
            if updtr_name in grp_updaters:
                raise ValueError(f"Duplicate updater name '{updtr_name}''. "
                            "An updater name must be unique within the group")
            updtr = {
                'name'      : updtr_name,
                'interval'  : cvt_intrvl_str_to_us(updtr_spec['interval']),
                'group'     : updtr_spec['group'],
                'sets'      : updtr_spec['sets'],
                'producers' : updtr_spec['producers']
            }
            if 'offset' in updtr_spec:
                updtr['offset'] = cvt_intrvl_str_to_us(updtr_spec['offset'])
            else:
                updtr['offset'] = None
            if 'auto' in updtr_spec and 'push' in updtr_spec:
                raise ValueError(f"The updater specification: {json.dumps(updtr_spec)} "
                                "contains both 'push' and 'auto' which are "
                                "mutually exclusive")
            if 'auto' in updtr_spec:
                updtr['auto'] = updtr_spec['auto']
            if 'push' in updtr_spec:
                updtr['push'] = updtr_spec['push']

            grp_updaters[updtr_name] = updtr
        return updaters

    def build_stores(self, config):
        """
        Return a dictionary keyed by the group name. Each dictionary
        entry is a list of stores in that group.
        """
        stores = {}
        if 'stores' not in config:
            return None
        for store_spec in config['stores']:
            self.check_required([ 'name', 'group', 'plugin', 'container', 'schema' ],
                                store_spec, '"store" entry')
            group = store_spec['group']
            if group not in stores:
                stores[group] = {}
            grp_stores = stores[group]
            store_name = store_spec['name']
            if store_name in grp_stores:
                raise ValueError(f"Duplicate store name '{store_name}''. "
                            "A store name must be unique within the group")

            self.check_required([ 'name', 'config'],
                             store_spec['plugin'],
                            '"store plugin" entry')
            grp_stores[store_name] = store_spec
        return stores

    def build_samplers(self, config):
        """
        Generate samplers from YAML config.
        Return a dictionary keyed by the samplers group name. Each dictionary
        entry is a single ldms daemon's sampler configuration.
        """
        smplrs = {}
        for smplr_spec in config['samplers']:
            self.check_required([ 'names' ],
                                  smplr_spec, '"sampler" entry')
            smplrs[smplr_spec['names']] = smplr_spec
        return smplrs

    def build_plugins(self, config):
        """
        Generate plugins to load from a YAML config.
        Return a dictionary keyed by the plugin's group name. Each dictionary entry
        is a single plugin's configuration.
        """
        plugins = {}
        for plugn_spec in config['plugins']:
            self.check_required([ 'name', 'config' ],
                                  plugn_spec, '"plugin" entry')
            group = plugn_spec['group']
            if group not in plugins:
                plugins[group] = {}
            grp_plugins = plugins[group]
            plugin_name = plugn_spec['name']
            if plugin_name in grp_plugins:
                raise ValueError(f'Duplicate plugin name "{plugin_name}". '
                                  'Plugin must be unique within a group.')
            grp_plugins[plugin_name] = plugn_spec
        return plugins

    def __init__(self, client, name, cluster_config):
        """
        """
        self.client = client
        self.name = name
        self.cluster_config = cluster_config
        self.endpoints = self.build_endpoints(cluster_config)
        self.aggregators = self.build_aggregators(cluster_config)
        self.groups = self.build_groups(cluster_config)
        self.producers = self.build_producers(cluster_config)
        self.updaters = self.build_updaters(cluster_config)
        self.stores = self.build_stores(cluster_config)
        if 'samplers' in cluster_config:
            self.samplers = self.build_samplers(cluster_config)
        else:
            self.samplers = None
        if 'plugins' in cluster_config:
            self.plugins = self.build_plugins(cluster_config)
        else:
            self.plugins = None

    def commit(self):
        pass

    def save_config(self):
        try:
            self.client.delete_prefix('/' + self.name)
            self.walk(self.endpoints, '/' + self.name + '/endpoints')
            self.walk(self.aggregators, '/' + self.name + '/aggregators')
            self.walk(self.groups, '/' + self.name + '/groups')
            self.walk(self.producers, '/' + self.name + '/producers')
            self.walk(self.updaters, '/' + self.name + '/updaters')
            self.walk(self.stores, '/' + self.name + '/stores')
            if 'samplers' in self.cluster_config:
                self.walk(self.samplers, '/' + self.name + '/samplers')
            if 'plugins' in self.cluster_config:
                self.walk(self.plugins, '/' + self.name + '/plugins')
            self.client.put('/'+self.name+'/last_updated', str(time.time()))
        except Exception as e:
            a, b, c = sys.exc_info()
            print(str(e)+' '+str(c.tb_lineno))
            return 1

    def parse_to_cfg_str(self, cfg_obj):
        cfg_str = ''
        for key in cfg_obj:
            if key != 'interval':
                if len(cfg_str) > 8:
                    cfg_str += ' '
                cfg_str += key + '=' + str(cfg_obj[key])
        return cfg_str

    def write_producers(self, fd, group_name):
        #Writes producer configuration to file fd
        if group_name in self.producers:
            ''' Balance samplers across aggregators '''
            prdcrs = []
            loop = round(len(self.producers[group_name]) / len(self.aggregators[group_name]))
            last_sampler = None
            for prdcr in self.producers[group_name]:
                prdcrs.append(prdcr["name"])
            if not last_sampler:
                idx = 0
            else:
                idx = prdcrs.index(last_sampler) + 1
            prod_group = self.producers[group_name][idx:]
            i = 0
            auth = self.endpoints[prod_group[0]['endpoint']]['auth']['name']
            auth_opt = self.endpoints[prod_group[0]['endpoint']]['auth']['conf']
            if auth:
                if len(auth_opt.split('=')) == 1:
                    auth_opt = 'conf='+auth_opt
                fd.write(f'auth_add name={auth} {auth_opt}\n')
            for producer in prod_group:
                if i >= loop:
                    break
                regex = False
                pname = producer['name']
                port = self.endpoints[producer['endpoint']]['port']
                xprt = self.endpoints[producer['endpoint']]['xprt']
                hostname = self.endpoints[producer['endpoint']]['addr']
                ptype = producer['type']
                interval = producer['reconnect']
                fd.write(f'prdcr_add name={pname} '+
                         f'host={hostname} '+
                         f'port={port} '+
                         f'xprt={xprt} type={ptype} interval={interval}\n')
                last_sampler = pname
                i += 1
                if 'regex' in producer:
                    regex = True
                    fd.write(f'prdcr_start_regex regex={producer["regex"]}\n')
                if not regex:
                    fd.write(f'prdcr_start_regex regex=.*\n')

    def write_samplers(self, fd, smplr_group):
        for sampler in self.samplers[smplr_group]['config']:
            cfg_str = self.parse_to_cfg_str(sampler)
            sname = sampler['name']
            interval = cvt_intrvl_str_to_us(sampler['interval'])
            fd.write(f'load name={sname}\n')
            fd.write(f'config {cfg_str} producer=${{HOSTNAME}} '+
                     f'component_id=${{COMPONENT_ID}} '+
                     f'instance=${{HOSTNAME}}/{sname}\n')
            if 'offset' in sampler:
                offset = cvt_intrvl_str_to_us(sampler['offset'])
                fd.write(f'start name={sname} interval={interval} offset={offset}\n')
            else:
                fd.write(f'start name={sname} interval={interval}\n')

    def write_sampler_plugins(self, group_name):
        if self.plugins != None:
            if group_name in self.plugins:
                fd = open(f'{path}/{group_name}-samplers.conf', 'w+')
                for plugin in self.plugins[group_name]:
                    cfg_str = self.parse_to_cfg_str(self.plugins[group_name][plugin]['config'])
                    fd.write(f'load name={plugin}\n')
                    fd.write(f'config name={plugin} {cfg_str}\n\n')
                fd.close()

    def write_agg_plugins(self, fd, group_name):
        # Write independent plugin configuration for group <group_name>
        if self.plugins != None:
            if group_name in self.plugins:
                for plugin in self.plugins[group_name]:
                    cfg_str = self.parse_to_cfg_str(self.plugins[group_name][plugin]['config'])
                    if 'stream' in self.plugins[group_name][plugin]['config']:
                        if 'regex' in self.plugins[group_name][plugin]['config']:
                            regex = self.plugins[group_name][plugin]['config']
                            fd.write(f'prdcr_subscribe stream={self.plugins[group_name][plugin]["config"]["stream"]} '\
                                     f'regex={regex}\n')
                        else:
                            fd.write(f'prdcr_subscribe stream={self.plugins[group_name][plugin]["config"]["stream"]} '\
                                     f'regex=.*\n')
                    fd.write(f'load name={plugin}\n')
                    fd.write(f'config name={plugin} {cfg_str}\n\n')

    def write_updaters(self, fd, group_name):
        if group_name in self.updaters:
            updtr_group = self.updaters[group_name]
            for updtr in updtr_group:
                interval = cvt_intrvl_str_to_us(updtr_group[updtr]['interval'])
                updtr_str = f'updtr_add name={updtr_group[updtr]["name"]} '
                if 'mode' in updtr_group[updtr]:
                    mode = updtr_group[updtr]['mode']
                else:
                    mode = 'static'
                # Check mode
                if mode == 'push':
                    updtr_str += 'push=onchange\n'
                elif mode == 'auto_interval':
                    updtr_str += 'auto_interval=True\n'
                elif 'offset' in updtr_group[updtr]:
                    offset = cvt_intrvl_str_to_us(updtr_group[updtr]['offset'])
                    fd.write(f'updtr_add name={updtr_group[updtr]["name"]} '+
                             f'interval={interval} offset={offset}\n')
                else:
                    fd.write(f'updtr_add name={updtr_group[updtr]["name"]} '+
                             f'interval={interval}\n')
                for prod in updtr_group[updtr]['producers']:
                    fd.write(f'updtr_prdcr_add name={updtr_group[updtr]["name"]} '+
                             f'regex={prod["regex"]}\n')
                fd.write(f'updtr_start name={updtr_group[updtr]["name"]}\n')

    def write_stores(self, fd, group_name):
        if group_name in self.stores:
            store_group = self.stores[group_name]
            loaded_plugins = []
            for store in store_group:
                if store_group[store]["plugin"]["name"] not in loaded_plugins:
                    fd.write(f'load name={store_group[store]["plugin"]["name"]}\n')
                    fd.write(f'config name={store_group[store]["plugin"]["name"]} '+
                             f'{self.parse_to_cfg_str(store_group[store]["plugin"]["config"])}\n')
                    loaded_plugins.append(store_group[store]["plugin"]["name"])
                strgp_add = f'strgp_add name={store} plugin={store_group[store]["plugin"]["name"]} '
                strgp_add += f'container={store_group[store]["container"]} '
                strgp_add += f'schema={store_group[store]["schema"]} '
                if 'flush' in store_group[store]:
                    strgp_add += f'flush={store_group[store]["flush"]}\n'
                else:
                    strgp_add += '\n'
                fd.write(strgp_add)
                fd.write(f'strgp_start name={store}\n')

    def config_v4(self, path):
        """
        Read the group configuration from ETCD and generate a version 4 LDMSD configuration
        This configuration assumes that the environemnt variables COMPONENT_ID, HOSTNAME
        all exist on the machines relevant to the ldmsd cluster.
        """
        for group_name in self.groups:
            # Load sampler statements
            group = self.groups[group_name]

            # Sampler config
            if self.samplers != None:
                try:
                    self.write_sampler_plugins(self)
                    for smplr_group in self.samplers:
                        # TO DO: Refactor sampler config architecture to more easily reference appropriate groups
                        if group_name != self.samplers[smplr_group]['group']:
                            continue
                        fd = open(f'{path}/{group_name}-samplers.conf', 'w+')
                        self.write_samplers(fd, smplr_group)
                    if fd:
                        fd.close()
                except Exception as e:
                    a, b, d = sys.exc_info()
                    print(f'Error generating sampler configuration: {str(e)} {str(d.tb_lineno)}')
                    raise ValueError
            else:
                print(f'"samplers" not found in configuration file. Skipping...')

            # Agg config
            try:
                ''' "Balance" agg configuration if all samplers are included in each aggregator '''
                if group_name not in self.aggregators:
                    continue
                last_sampler = None
                for agg in self.aggregators[group_name]:
                    fd = open(f'{path}/{group_name}-{agg["name"]}.conf', 'w+')
                    self.write_producers(fd, group_name)
                    self.write_agg_plugins(fd, group_name)
                    self.write_updaters(fd, group_name)
                    self.write_stores(fd, group_name)
            except Exception as e:
                ea, eb, ec = sys.exc_info()
                print('Agg config Error: '+str(e)+' Line:'+str(ec.tb_lineno))
                raise ValueError

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="LDMS Monitoring Cluster Configuration")
    parser.add_argument("--cluster", metavar="FILE", required=True,
                        help="The name of the etcd cluster configuration file")
    parser.add_argument("--ldms_config", metavar="FILE", required=True,
                        help="The ldmsd load balance domain configuration file. "
                        "This will not start the maestro "
                        "load balancer")
    parser.add_argument("--prefix", metavar="STRING", required=True,
                        help="The prefix for the dumped aggregator configurations",
                        default="unknown")
    parser.add_argument("--generate-config-path", metavar="STRING", required=False,
                        default=False)
    parser.add_argument("--version", metavar="VERSION",
                        help="The OVIS version for the output syntax (4 or 5), default is 4",
                        default=4)
    args = parser.parse_args()

    # Load the cluster configuration file. This configures the daemons
    # that support the key/value configuration database
    etcd_fp = open(args.cluster)
    etcd_spec = yaml.safe_load(etcd_fp)

    pfx = etcd_spec['cluster']
    etcd_hosts = ()
    for h in etcd_spec['members']:
        etcd_hosts += (( h['host'], h['port'] ),)

    # All keys in the DB are prefixed with the cluster name, 'pfx'. So we can
    # have multiple monitoring hosted by the same consensus cluster.
    config_fp = open(args.ldms_config)
    conf_spec = yaml.safe_load(config_fp)

    # Use the 1st host for now
    client = etcd3.client(host=etcd_hosts[0][0], port=etcd_hosts[0][1],
        grpc_options=[ ('grpc.max_send_message_length',16*1024*1024),
                       ('grpc.max_receive_message_length',16*1024*1024)])

    cluster = Cluster(client, args.prefix, conf_spec)
    if args.generate_config_path:
        cluster.config_v4(args.generate_config_path)
        print("LDMSD v4 config files generated")
        sys.exit(0)

    # blow away the existing configuration
    rc = cluster.save_config()
    if rc:
        print("Error saving ldms cluster configuration to etcd cluster")
        sys.exit(0)
    print("LDMS aggregator configuration saved to etcd cluster.")

    sys.exit(0)
