daemons:
  - names : &samplers "sampler-[1-8]"
    hosts : &node-hosts "node-[01-08]"
    endpoints :
      - names : &sampler-endpoints "node-[01-08]-[10002]"
        ports : &sampler-ports "[10002]"
        maestro_comm : True
        xprt  : sock
        auth  :
           name : ovis
           conf : /home/nick/projects/old-maestro/secret.conf

      - names : &sampler-rdma-endpoints "node-[01-08]-10002/rdma"
        ports : *sampler-ports
        maestro_comm : False
        xprt  : rdma
        auth  :
          name : munge

  - names : &l1-agg "l1-aggs-[1-8]"
    hosts : &l1-agg-hosts "node-[01-08]"
    endpoints :
      - names : &l1-agg-endpoints "node-[01-08]-[10101]"
        ports : &agg-ports "[10101]"
        maestro_comm : True
        xprt  : sock
        auth  :
          name : munge

aggregators:
  - daemons   : *l1-agg
    peers     :
      - daemons   : *samplers
        endpoints : *sampler-endpoints
        reconnect : 20s
        type      : active
        updaters  :
          - mode     : pull
            interval : "1.0s"
            offset   : "0ms"
            sets     :
              - regex : .*
                field : inst
    subscribe : # Aggregator stream subscriptions
      - stream : kokkos-perf-data # Stream name
        regex : .* # Regular expression that matches producer names
    plugins   :
      - name   : kokkos_appmon_store
        config : { path : /storage/eclipse/sos/ldms-data, stream : kokkos-perf-data }

samplers:
  - daemons : *samplers
    plugins :
      - name        : meminfo # Variables can be specific to plugin
        interval    : 1.0s # Used when starting the sampler plugin
        offset      : "0s"
        config :
            schema : meminfo
            component_id : "${LDMS_COMPONENT_ID}"
            producer : "${HOSTNAME}"
            instance : "${HOSTNAME}/meminfo-test" # If not defined <prdcr_name>/<plugin name> will be used
            perm : "0777"

      - name        : vmstat
        interval    : "2.0s"
        offset      : "1ms"
        config :
            schema : vmstat
            component_id : "${LDMS_COMPONENT_ID}"
            producer : "${HOSTNAME}"
            perm  : "0777"

      - name        : procstat
        interval    : "4.0s"
        offset      : 2ms
        config :
            schema : procstat
            component_id : "${LDMS_COMPONENT_ID}"
            producer : "${HOSTNAME}"
            perm : "0777"

stores:
  - name      : sos-meminfo
    daemons   : *l1-agg
    container : ldms_data
    schema    : meminfo
    flush     : 10s
    plugin :
      name   : store_sos
      config : { path : /DATA }

  - name      : sos-vmstat
    daemons   : *l1-agg
    container : ldms_data
    schema    : vmstat
    flush     : 10s
    plugin :
      name   : store_sos
      config : { path : /DATA }

  - name      : sos-procstat
    daemons   : *l1-agg
    container : ldms_data
    schema    : procstat
    flush     : 10s
    plugin :
      name   : store_sos
      config : { path : /DATA }

